name: Build & Deploy to GH Pages

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: "Check out repo"
      uses: actions/checkout@v3

    - name: "Run build scripts"
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        chmod +x build.sh build/*.sh
        ./build.sh

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        single-commit: true
        folder: .
